name: Android CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [34]
        target: [google_apis]
        arch: [x86_64]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Create key.properties from secrets
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "${{ secrets.KEY_PROPERTIES_PRD }}" > key.properties
          else
            echo "${{ secrets.KEY_PROPERTIES_DEV }}" > key.properties
          fi

      - name: Decode google-services.json
        run: |
            echo "${{ secrets.GOOGLE_SERVICE_JSON }}" | base64 -d > app/google-services.json

      - name: Debug key.properties (oculta valores sensibles)
        run: |
          grep BASE_URL key.properties | sed 's/=.*/=*** (hidden) *** /'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Lint
        run: ./gradlew lint --no-daemon

      - name: Run Ktlint
        run: ./gradlew ktlintCheck --no-daemon

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --continue --no-daemon

      - name: Build project
        run: ./gradlew assembleDebug

